# 这是一个临时性用来构建测试包的action

name: Build Action Release

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=23.7.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: vue-tsc check
        run: pnpm check
        continue-on-error: true

      - name: Build Output
        run: |
          pnpm build:dist
          pnpm build:dist-firefox

      - name: Zip build
        run: |
            cd dist-chrome
            zip -r ../dist-chrome.zip *
            cd ../dist-firefox
            zip -r ../dist-firefox.zip *

      - name: Upload Built Zip to action
        uses: actions/upload-artifact@v4
        with:
          path: |
            dist-chrome.zip
            dist-firefox.zip
